#+TITLE: Этический кодекс twitter
#+LANGUAGE: ru

* Языковые различия 

У нас часто встречаются различия между информацией и некоторыми терминами.

Это связано скорее с разным языком, культурой и развитием стран.

И у них нет такого понятия как Этический кодекс или в переводе на
английский: code of ethics

У них есть code of conduct, что также можно перевести как кодекс деловой этики,
но чаще встречается как кодекс поведения.

* Twitter?

Twitter - это социальная сеть, которая популярна во всём мире, в том числе у нас(сейчас он у нас заблокирован,
в связи последними событиями в мире)

На этой платформе, как и на других социальных сетя, люди, в основном делятся мнением, обсуждают их,
а также развлекаются и
в целом соцаилизуруются между собой.

* Обязательство

Мы считаем, что Сообщество разработчиков Twitter должно поддерживать позитивный и инклюзивный опыт для всех.
Twitter стремится обеспечить дружественную,
безопасную и гостеприимную обстановку для всех участников и ожидает,
что все будут относиться друг к другу с уважением и вежливостью.

В следующем Кодексе поведения изложены наши ожидания в отношении поведения участников,
а также последствия для неприемлемого поведения. Мы требуем,
чтобы все участники соблюдали этот Кодекс в Сообществе и на любых мероприятиях, связанных с сообществом.

* Ожидаемое поведение

- Относитесь к другим с достоинством и уважением.

- Воздерживаться от унизительного или дискриминационного поведения и речи.

- Помните о своем окружении и своих коллегах-участниках.

- Оповещение сотрудников Twitter, если вы заметили опасную ситуацию или кого-то,
   кто находится в бедственном положении.


* Неприемлимое поведение

- Запугивание

- Преследование

- Обида

- Дискриминация

- Отступничество или унижение


* При этих действиях

Если считается, что кто-то действует неприемлемым образом,
сотрудники могут предпринять любые действия,
которые они сочтут целесообразными,
включая удаление любого лица из собраний или связанных с ними событий без предупреждения,
в зависимости от обстоятельств.

Если вы подвержены неприемлемому поведению, обратите внимание,
что кто-то другой подвергается неприемлемому поведению или имеет какие-либо другие проблемы,
пожалуйста, сообщите об этом сотрудникам Twitter как можно скорее. Мы ценим вашу посещаемость и участие и
с нетерпением ждем вашего вступления в наше сообщество.

* Итоги

Как мы можем заметить данная платформа придерживается западной культуры и политики, но некоторые утверждения,
если не уходить в **крайности** верны и я считаю должны исполняться везде не только в сообществе разработчиков
Твиттера.
